apiVersion: apps/v1
kind: Deployment
metadata:
  name: extra-credit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image1
  template:
    metadata:
      labels:
        app: image1
    spec:
      containers:
      - name: M16447456container
        image: image1:latest # Replace with your Docker image name
        ports:
        - containerPort: 8080